version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.5/site-packages/
      - run: python3 unit-testing/basic-example.py
      - run: sudo pip install nose